### PR TITLE
Change to default navigation menu

### PR DESCRIPTION
**Pull request by kdelfour**
This change allow you to use the default navigation menu for all ghost > 0.5.9

### CODE REVIEW

**Comment by epistrephein** [comment]
Hi, can you please undo your commit to README so that I can merge your work into the repo?

**Comment by kdelfour** [comment]
Undo this pull request, I have change a lots of things on this theme, I'm going to fork again your repo and I will pull only the change to the navigation menu. OK?

**Comment by kdelfour** [comment]
I'm going to tag my version and I'm going to revert all changes to allow you to merge.

**Comment by epistrephein** [comment]
Perfect, thanks :smile:

**Comment by kdelfour** [comment]
It's done, you can merge. Say me if it's Ok for you..

**Pull request closed without merging**
